export enum TodoActionsTypes {
  GET_ALL_TODO = 'GET_ALL_TODO',
  GET_ALL_TODO_SUCCESS = 'GET_ALL_TODO_SUCCESS',
  GET_ALL_TODO_ERROR = 'GET_ALL_TODO_ERROR',
  ADD_TODO = 'ADD_TODO',
  UPDATE_TODO = 'UPDATE_TODO',
  DELETE_TODO = 'DELETE_TODO',
  DELETE_ALL_TODO = 'DELETE_ALL_TODO',
}
